(function(){'use strict';
const V='MMA_MANAGER_V1_FIGHT_CONTRACT';
if(window.__MM_V1_FIGHT_CONTRACT)return; window.__MM_V1_FIGHT_CONTRACT=true;
function getF(){try{return typeof currentF==='function'?currentF():null}catch(e){return null}}
function saveSafe(){try{if(typeof save==='function')save()}catch(e){}}
function fmt(n){return Number(n||0).toLocaleString('ru-RU')}
function sig(f){const x=f&&f.nextFight;if(!x)return '';return [x.org,x.opponent?.id||x.opponent?.name||'',x.date,x.purse,x.titleFight?'T':'N'].join('|')}
function closeSafe(){try{if(typeof closeModal==='function')closeModal();else document.getElementById('modal')?.classList.remove('open')}catch(e){}}
function openContract(f){const x=f?.nextFight;if(!x)return;const purse=Number(x.purse||0);const winBonus=Number(x.winBonus||purse);const ppv=Number(x.ppvPercent||((x.titleFight||Number(x.rank||999)<=5)?2:(Number(x.rank||999)<=15?1:0.5)));x.contractTerms={type:'ONE_FIGHT',purse,winBonus,ppvPercent:ppv,signed:false};saveSafe();const modal=document.getElementById('modal'),sheet=document.getElementById('sheet');if(!modal||!sheet)return;modal.classList.add('open');sheet.innerHTML=`<div class="eyebrow">КОНТРАК НА БОЙ</div><div class="title">${f.name} vs ${x.opponent?.name||'Соперник'}</div><div class="muted">${x.org||'Организация'} • ${x.type||'Бой'} • ${typeof dateLabel==='function'?dateLabel(x.date):'Дата боя'}</div><section class="panel"><div class="notice-strip">Переговоры завершены. Организация подготовила контракт на один бой. Проверь условия перед подписанием.</div><div class="row"><span>Гонорар за выход</span><b>$${fmt(purse)}</b></div><div class="row"><span>Бонус за победу</span><b>$${fmt(winBonus)}</b></div><div class="row"><span>PPV</span><b>${ppv}%</b></div><div class="row"><span>Соперник</span><b>#${x.rank||'—'} • ${x.opponent?.name||''}</b></div><div class="row"><span>Раунды</span><b>${x.rounds||3}</b></div><div class="row"><span>Тип</span><b>${x.type||'Бой'}</b></div><div class="row"><span>Дата</span><b>${typeof dateLabel==='function'?dateLabel(x.date):x.date}</b></div></section><div class="sheet-actions"><button data-contract-cancel>Назад</button><button class="primary" data-contract-sign>Подписать бой</button></div>`;sheet.querySelector('[data-contract-sign]').onclick=()=>{x.contractTerms.signed=true;x.signedFightContract=true;saveSafe();closeSafe();try{if(typeof notify==='function')notify(`${f.name}: контракт на бой подписан.`)}catch(e){}try{if(typeof toast==='function')toast('Контракт на бой подписан')}catch(e){}};sheet.querySelector('[data-contract-cancel]').onclick=()=>{closeSafe()}}
let initialized=false,seen='';
function tick(){const f=getF();if(!f){setTimeout(tick,400);return}const s=sig(f);if(!initialized){seen=s;initialized=true;setTimeout(tick,400);return}if(s&&s!==seen&&!f.nextFight?.signedFightContract){seen=s;openContract(f)}else if(!s){seen=''}setTimeout(tick,350)}
setTimeout(tick,500);
})();