(function(){'use strict';
const V='MMA_MANAGER_V64_ORGANIZATION';
if(window.__MM_V64_ORG)return; window.__MM_V64_ORG=true;
function F(){try{return typeof currentF==='function'?currentF():null}catch(e){return null}}
function day(){return Number(s.day||1)}
function num(x,d=0){return Number.isFinite(Number(x))?Number(x):d}
function rank(f,org){try{const arr=s.rankingsByOrg?.[org]?.[f.weight]||[];return arr.find(x=>x.id===f.id)?.rank||999}catch(e){return 999}}
function champ(f){return !!f?.title}
function isAvailable(x){return x&&!x.retired&&!x.injury&&!x.nextFight&&!x.agencyManaged}
function cooldown(f){return num(f.offerCooldownUntil,0)>day()}
function notifyPersonal(text,type='MATCHMAKING'){try{if(typeof notify==='function')notify(text)}catch(e){}try{if(typeof logNews==='function')logNews(text,type)}catch(e){}try{if(typeof toast==='function')toast(text)}catch(e){}}
function ensureV64(f){if(!f)return;f.organizationOffers=Array.isArray(f.organizationOffers)?f.organizationOffers:[];f.refusalHistory=Array.isArray(f.refusalHistory)?f.refusalHistory:[];f.refusalStats=f.refusalStats||{freeOffersRejected:0,contractOffersRejected:0,windowStart:day(),lastRefusalDay:0};f.reputationHooks=f.reputationHooks||{accepted:0,refused:0,majorRefusals:0}}
function pruneHistory(f){ensureV64(f);f.refusalHistory=f.refusalHistory.filter(x=>day()-num(x.day)>365);f.organizationOffers=f.organizationOffers.filter(x=>num(x.expires,0)>=day()&&!x.resolved)}
function resetRefusalWindow(f){ensureV64(f);const st=f.refusalStats;if(!st.windowStart||day()-st.windowStart>120){st.windowStart=day();st.contractOffersRejected=0;st.freeOffersRejected=0}}
function freePenalty(count){if(count<=0)return 0;if(count===1)return rand(10,20);if(count===2)return rand(20,50);if(count===3)return rand(50,90);return rand(100,120)}
function registerFreeRefusal(f,rejected,total){ensureV64(f);resetRefusalWindow(f);const r=Math.max(1,rejected),t=Math.max(r,total||r);f.refusalStats.freeOffersRejected+=r;f.refusalStats.lastRefusalDay=day();f.refusalHistory.push({day:day(),type:'free',rejected:r,total:t,orgs:[]});f.reputationHooks.refused+=r;if(r>=3)f.reputationHooks.majorRefusals++;const days=freePenalty(r);f.offerCooldownUntil=Math.max(num(f.offerCooldownUntil,0),day()+days);notifyPersonal(`${f.name}: после отказа от ${r} предложения${r===1?'':'й'} новые предложения не будут поступать ${days} дней.`,'REFUSAL');save()}
function registerContractRefusal(f,offer,reason){ensureV64(f);resetRefusalWindow(f);const c=f.contract;if(!c)return;c.refusalHistory=Array.isArray(c.refusalHistory)?c.refusalHistory:[];c.refusalCount=num(c.refusalCount,0)+1;c.refusalWindowStart=c.refusalWindowStart||day();c.lastRefusalDay=day();const serious=!!offer?.titleFight||champ(f)||num(offer?.opponentRank,999)<=3;c.refusalHistory.push({day:day(),opponent:offer?.opponent?.name||'',rank:offer?.opponentRank||999,titleFight:!!offer?.titleFight,reason:reason||'Без причины'});f.refusalHistory.push({day:day(),type:'contract',org:c.org,rejected:1,total:1,major:serious,titleFight:!!offer?.titleFight});f.reputationHooks.refused++;if(serious)f.reputationHooks.majorRefusals++;if(serious)c.majorRefusals=num(c.majorRefusals,0)+1;const n=c.refusalCount;if(champ(f)){c.championRefusals=num(c.championRefusals,0)+1;if(c.championRefusals===1){c.refusalWarning=1;notifyPersonal(`${f.name}: организация недовольна отказом чемпиона от боя. Получено предупреждение.`,'CONTRACT')}else if(c.championRefusals===2){c.refusalWarning=2;notifyPersonal(`${f.name}: последнее предупреждение. Следующий необоснованный отказ чемпиона поставит титул под угрозу.`,'CONTRACT')}else if(c.championRefusals===3){c.titleDefenseUltimatum=day()+30;notifyPersonal(`${f.name}: организация требует защитить титул в ближайшие 30 дней. Титул под угрозой.`,'CONTRACT')}else if(c.championRefusals===4){if(f.title?.org===c.org&&typeof clearTitle==='function')clearTitle(c.org,f.weight);f.title=null;f.careerStage='Contender';c.titleStrippedDay=day();notifyPersonal(`${f.name}: организация лишила чемпиона титула из-за неоднократных отказов.`,'TITLE')}else if(c.championRefusals>=5){const old=c.org;f.formerContractOrg=old;f.contract=null;f.leagueFired=true;f.leagueFiredDay=day();f.currentFightLeague=null;notifyPersonal(`${old}: контракт с ${f.name} расторгнут после серии отказов чемпиона.`,'CONTRACT')}}else if(n===1){c.refusalWarning=1;notifyPersonal(`${f.name}: ${c.org} вынесла предупреждение за отказ от боя.`,'CONTRACT')}else if(n===2){c.refusalWarning=2;notifyPersonal(`${f.name}: последнее предупреждение от ${c.org}. Частые отказы могут привести к увольнению.`,'CONTRACT')}else if(n>=3){const old=c.org;f.formerContractOrg=old;f.contract=null;f.leagueFired=true;f.leagueFiredDay=day();f.currentFightLeague=null;if(f.title?.org===old){if(typeof clearTitle==='function')clearTitle(old,f.weight);f.title=null;f.careerStage='Contender'}notifyPersonal(`${old}: контракт с ${f.name} расторгнут из-за частых отказов от боёв.`,'CONTRACT')}save()}
function acceptanceBonus(f){ensureV64(f);if(f.contract){f.contract.refusalCount=Math.max(0,num(f.contract.refusalCount)-1);if(f.contract.refusalCount===0)f.contract.refusalWarning=0}f.reputationHooks.accepted++;save()}
function candidatePool(f,org){const pool=(s.world||[]).filter(x=>isAvailable(x)&&x.id!==f.id&&x.weight===f.weight&&(x.org===org.name||x.orgLevel===org.level));const rankArr=s.rankingsByOrg?.[org.name]?.[f.weight]||[];const rm=new Map(rankArr.map(x=>[x.id,x.rank]));const fr=rank(f,org.name),isC=champ(f);let filtered=pool.filter(x=>{const r=rm.get(x.id)||999;if(isC)return r>=1&&r<=5;if(fr<=5)return r>=1&&r<=10;if(fr<=15)return r>=Math.max(1,fr-7)&&r<=fr+7;return Math.abs(num(x.rating,ovr(x))-ovr(f))<=13});if(!filtered.length)filtered=pool.filter(x=>Math.abs(ovr(x)-ovr(f))<=16);filtered.sort((a,b)=>{const ra=rm.get(a.id)||999,rb=rm.get(b.id)||999;if(isC)return ra-rb;return Math.abs(ra-fr)-Math.abs(rb-fr)||Math.abs(ovr(a)-ovr(f))-Math.abs(ovr(b)-ovr(f))});const recent=new Set((f.history||[]).slice(0,4).map(h=>h.opponent));return filtered.filter(x=>!recent.has(x.name))}
function offerFor(f,org,o){const r=rank(o,org.name),fr=rank(f,org.name),isC=champ(f),holder=typeof titleHolder==='function'?titleHolder(org.name,f.weight):null,title=!!(holder&&holder.id===o.id&&(isC||(!f.contract&&num(f.winStreak,0)>=5)));const base=typeof contractTerms==='function'?contractTerms(f,org):{purse:org.purse||1000};let purse=Math.max(250,Math.round(num(base.purse,org.purse||1000)*(0.78+Math.random()*0.38)));if(title)purse=Math.round(purse*1.8);if(fr<=5&&r<=5)purse=Math.round(purse*1.35);return{id:'O'+Date.now()+Math.random(),org:org.name,short:org.short,opponent:{...o},opponentRank:r,ranked:r<999,type:title?'ТИТУЛЬНЫЙ БОЙ':(r<999?'РЕЙТИНГОВЫЙ БОЙ':'ОБЫЧНЫЙ БОЙ'),titleFight:title,rounds:title?5:3,date:day()+rand(14,45),purse,event:choice(['Fight Night','Championship Series','Main Event','Fight Night Series'])+' #'+rand(10,99),expires:day()+7}}
function generateOffers(f){ensureV64(f);pruneHistory(f);if(cooldown(f)){toast(`${f.name}: новые предложения временно недоступны ещё ${f.offerCooldownUntil-day()} дн.`);return[]}if(f.nextFight){toast('У бойца уже есть назначенный бой');return[]}if(f.contract&&num(f.contract.fightsLeft,0)<=0){toast(`Контракт с ${f.contract.org} исчерпан.`);return[]}const contracted=!!f.contract;let orgs=contracted?ORGS.filter(o=>o.name===f.contract.org):ORGS.filter(o=>o.name!=='DWCS'&&(s.managerRating||30)>=Math.max(20,o.unlock-10));if(!contracted)orgs=orgs.filter(o=>!isTopLeague(o.name)||topLeagueEligible(f,o.name));const count=contracted?rand(1,3):rand(1,5);let offers=[];const used=new Set();for(let i=0;i<orgs.length&&offers.length<count;i++){let org=orgs.slice().sort(()=>Math.random()-.5).find(o=>!used.has(o.name));if(!org)break;used.add(org.name);const pool=candidatePool(f,org);if(!pool.length)continue;offers.push(offerFor(f,org,pool[0]))}if(!contracted&&offers.length<count){const all=orgs.flatMap(org=>candidatePool(f,org).slice(0,4).map(o=>offerFor(f,org,o))).sort(()=>Math.random()-.5);const usedPairs=new Set(offers.map(x=>x.org+'|'+x.opponent.id));for(const x of all){if(offers.length>=count)break;const k=x.org+'|'+x.opponent.id;if(usedPairs.has(k))continue;usedPairs.add(k);offers.push(x)}}f.organizationOffers=offers;save();return offers}
function renderOfferList(f,offers){const contracted=!!f.contract;document.getElementById('modal').classList.add('open');const penalty=contracted?`Контракт: ${f.contract.org} • осталось боёв: ${f.contract.fightsLeft}/${f.contract.length}`:`Свободный агент • предложения могут быть из разных лиг`;document.getElementById('sheet').innerHTML=`<div class="eyebrow">ОРГАНИЗАЦИЯ БОЯ • ${contracted?'КОНТРАК':'FREE AGENT'}</div><div class="title">Предложения для ${f.name}</div><div class="muted">${penalty}</div><section class="panel"><div class="notice-strip">${contracted?`Лига ${f.contract.org} предлагает ${offers.length} бой${offers.length===1?'':'а'}. Другие организации недоступны по контракту.`:`Свободному бойцу доступно ${offers.length} одноразовых предложени${offers.length===1?'е':'й'} от разных лиг.`}</div></section><div class="list">${offers.map((x,i)=>`<div class="scout"><div class="fighter-top"><div class="scout-face">${emoji(x.opponent.style)}</div><div class="fighter-info"><div class="fighter-name">${x.opponent.flag||'🌍'} ${x.opponent.name}</div><div class="fighter-sub">${x.org} • ${x.opponent.country} • ${rec(x.opponent)} • #${x.opponentRank||'—'}</div></div><div class="score">${ovr(x.opponent)}</div></div><div class="tags"><span class="tag">${x.org}</span><span class="tag">${x.type}</span><span class="tag">${x.rounds} раундов</span><span class="tag">${dateLabel(x.date)}</span><span class="tag">$${x.purse.toLocaleString('ru-RU')}</span></div><div class="scout-actions"><button data-v64-profile="${i}">Профиль</button><button class="primary" data-v64-offer="${i}">Переговоры</button><button class="red" data-v64-refuse="${i}">Отказаться</button></div></div>`).join('')}</div><div class="sheet-actions"><button data-v64-close>Закрыть</button></div>`;document.querySelector('[data-v64-close]').onclick=closeModal;document.querySelectorAll('[data-v64-profile]').forEach(b=>b.onclick=()=>profile(offers[+b.dataset.v64Profile].opponent,'match'));document.querySelectorAll('[data-v64-offer]').forEach(b=>b.onclick=()=>negotiateOffer(f,offers[+b.dataset.v64Offer]));document.querySelectorAll('[data-v64-refuse]').forEach(b=>b.onclick=()=>refuseOffer(f,offers[+b.dataset.v64Refuse],offers.length))}
function negotiateOffer(f,o){const min=Math.max(250,Math.round(o.purse*.65)),max=Math.max(min,Math.round(o.purse*1.65));document.getElementById('sheet').innerHTML=`<div class="eyebrow">ПЕРЕГОВОРЫ ПО БОЮ</div><div class="title">${f.name} vs ${o.opponent.name}</div><div class="muted">${o.org} • ${o.type} • ${dateLabel(o.date)}</div><section class="panel"><div class="row"><span>Предложено</span><b>$${o.purse.toLocaleString('ru-RU')}</b></div><div class="row"><span>Соперник</span><b>#${o.opponentRank||'—'} • ${rec(o.opponent)}</b></div><div><label class="muted">Твой гонорар, $</label><input id="v64Salary" class="input" type="number" min="${min}" max="${max}" value="${o.purse}"></div><div class="notice-strip">Сумма выше предложения снижает шанс согласия лиги.</div></section><div class="sheet-actions"><button data-v64-back>Назад</button><button class="primary" data-v64-propose>Договориться</button></div>`;document.querySelector('[data-v64-back]').onclick=()=>renderOfferList(f,f.organizationOffers||[]);document.querySelector('[data-v64-propose]').onclick=()=>{const purse=Math.max(min,Math.min(max,Number(document.getElementById('v64Salary').value)||o.purse));const chance=Math.max(15,Math.min(98,Math.round(86-Math.max(0,purse-o.purse)/Math.max(1,o.purse)*70+(f.reputationHooks?.accepted||0)*.2)));if(Math.random()*100>chance){notifyPersonal(`${o.org}: условия по бою с ${o.opponent.name} не согласованы.`,'NEGOTIATION');return}acceptFight(f,o,purse)}}
function acceptFight(f,o,purse){f.organizationOffers=[];f.leagueOffers=[];f.fightResolved=false;f.nextFight={opponent:{...o.opponent},org:o.org,event:o.event,rounds:o.rounds,date:o.date,purse,rank:o.opponentRank,ranked:o.ranked,type:o.type,titleFight:o.titleFight,venue:choice(['Las Vegas Arena','Abu Dhabi Arena','Moscow Arena','Las Vegas','New York','Riyadh Arena']),card:o.rounds===5?'MAIN EVENT':choice(['PRELIMS','MAIN CARD','CO-MAIN EVENT']),oneFight:!f.contract};f.preferredCampStyle=f.preferredCampStyle||null;f.campStyle=f.preferredCampStyle||defaultCampStyleForFighter(f);f.campPerformance=f.campStyle==='peak'?8:(f.campStyle==='conditioning'?5:3);f.campWeek=1;f.campSchedule={};f.currentFightLeague=o.org;if(f.contract)f.contract.fightsLeft=Math.max(0,num(f.contract.fightsLeft,1)-1);acceptanceBonus(f);if(o.titleFight&&f.contract)f.contract.championFightHistory=(f.contract.championFightHistory||[]).concat([{day:day(),opponent:o.opponent.name,rank:o.opponentRank}]);notifyPersonal(`${f.name}: бой согласован — ${o.org} vs ${o.opponent.name}.`,'FIGHT');save();closeModal();page('home')}
function refuseOffer(f,o,total){const arr=(f.organizationOffers||[]).filter(x=>x.id!==o.id);f.organizationOffers=arr;if(f.contract){registerContractRefusal(f,o,'Отказ менеджера от предложенного боя')}if(!f.contract&&!arr.length){registerFreeRefusal(f,total,total)}else if(!f.contract){f.reputationHooks.refused++;f.refusalHistory.push({day:day(),type:'free_partial',rejected:1,total})}save();if(!f.contract&&arr.length){renderOfferList(f,arr);toast('Предложение отклонено. Остальные предложения остаются.');return}closeModal();page('home')}
function v64Matchmake(){const f=F();if(!f){toast('Выбери бойца');return}ensureV64(f);pruneHistory(f);if(!f.agencyManaged){toast('Сначала подпиши бойца в своё агентство');return}if(f.nextFight){toast('У бойца уже есть назначенный бой');return}if(cooldown(f)){toast(`${f.name}: новые предложения будут доступны через ${f.offerCooldownUntil-day()} дн.`);return}const offers=generateOffers(f);if(!offers.length){toast(f.contract?`В ${f.contract.org} сейчас нет подходящего предложения.`:'Сейчас нет подходящих предложений. Попробуй позже.');return}renderOfferList(f,offers)}
window.matchmake=v64Matchmake;window._matchmakeHeavy=v64Matchmake;
const oldProfile=window.profile;window.profile=function(f,back){try{oldProfile(f,back);const sh=document.getElementById('sheet');if(!sh||!f)return;ensureV64(f);const box=document.createElement('section');box.className='panel';box.innerHTML=`<div class="section-head"><h3>Организация боёв</h3><span>${f.contract?f.contract.org:'FREE'}</span></div><div class="row"><span>Предложения</span><b>${f.organizationOffers.length}</b></div>${f.offerCooldownUntil>day()?`<div class="notice-strip">Новые предложения через ${f.offerCooldownUntil-day()} дн.</div>`:''}${f.contract?`<div class="row"><span>Отказы за период</span><b>${f.contract.refusalCount||0}</b></div>${f.contract.refusalWarning===2?'<div class="notice-strip">Последнее предупреждение лиги.</div>':''}`:''}</section>`;const anchor=[...sh.querySelectorAll('.panel')].find(x=>(x.innerText||'').includes('Контракт'));if(anchor)anchor.after(box);else sh.appendChild(box)}catch(e){console.warn(V,e)}};
window.MMA_MANAGER_V64_ORGANIZATION=true;
})();
