(function(){'use strict';
const V='MMA_MANAGER_V64_ORGANIZATION_FIXED4';
if(window.__MM_V64_ORG4)return;window.__MM_V64_ORG4=true;
function S(){try{return typeof s!=='undefined'?s:window.s}catch(e){return window.s||{}}}
function F(){try{return typeof currentF==='function'?currentF():null}catch(e){return null}}
function day(){return Number(S()?.day||1)}
function n(x,d=0){const v=Number(x);return Number.isFinite(v)?v:d}
function msg(t){try{if(typeof notify==='function')notify(t)}catch(e){}try{if(typeof toast==='function')toast(t)}catch(e){}}
function saveSafe(){try{if(typeof save==='function')save()}catch(e){}}
function closeSafe(){try{if(typeof closeModal==='function')closeModal();else document.getElementById('modal')?.classList.remove('open')}catch(e){}}
function rank(f,org){try{const a=S()?.rankingsByOrg?.[org]?.[f.weight]||[];const q=a.find(x=>x.id===f.id);return q?.rank||999}catch(e){return 999}}
function champ(f){return !!f?.title}
function ensure(f){if(!f)return;f.organizationOffers=Array.isArray(f.organizationOffers)?f.organizationOffers:[];f.refusalHistory=Array.isArray(f.refusalHistory)?f.refusalHistory:[];f.reputationHooks=f.reputationHooks||{accepted:0,refused:0,majorRefusals:0};}
function available(x){return x&&!x.retired&&!x.injury&&!x.nextFight&&!x.agencyManaged}
function weightOf(x){return x?.weight??x?.weightClass??x?.division??x?.weightCategory??x?.weight_class??x?.weightClassName??null}
function weightKey(x){const w=weightOf(x);if(w===null||w===undefined||w==='')return '';return String(w).toLowerCase().replace(/[\s_-]+/g,'')}
function sameWeight(a,b){const A=weightKey(a),B=weightKey(b);if(!A||!B)return !A&&!B;return A===B||A.replace(/\.0$/,'')===B.replace(/\.0$/,'')}
function fighterSources(){const z=S();const out=[];const add=a=>{if(Array.isArray(a))for(const x of a)if(x&&typeof x==='object')out.push(x)};add(z.world);add(z.roster);add(z.fighters);add(z.allFighters);add(z.freeAgents);add(window.world);add(window.roster);const m=new Map();for(const x of out){const k=x.id??x.uid??x.name;if(k!==undefined&&!m.has(String(k)))m.set(String(k),x)}return [...m.values()]}
function orgList(){let a=[];try{a=typeof ORGS!=='undefined'&&Array.isArray(ORGS)?ORGS:[]}catch(e){a=Array.isArray(window.ORGS)?window.ORGS:[]}return a.filter(Boolean)}
function candidatePool(f,org){const all=fighterSources().filter(x=>available(x)&&x.id!==f.id&&sameWeight(x,f));const recent=new Set((f.history||[]).slice(0,4).map(h=>h.opponent));let pool=all.filter(x=>!recent.has(x.name));let orgPool=pool.filter(x=>x.org===org.name||x.orgLevel===org.level||x.currentOrg===org.name||x.league===org.name);if(orgPool.length)pool=orgPool;const fr=rank(f,org.name);let ranked=pool.filter(x=>{const r=rank(x,org.name);if(champ(f))return r>=1&&r<=5;if(fr<=5)return r>=1&&r<=10;if(fr<=15)return r>=Math.max(1,fr-7)&&r<=fr+7;return true});if(!ranked.length)ranked=pool;if(!ranked.length){ranked=all.filter(x=>!recent.has(x.name));}if(!ranked.length){ranked=fighterSources().filter(x=>available(x)&&x.id!==f.id&&!recent.has(x.name)&&sameWeightLoose(x,f));}return ranked}
function sameWeightLoose(a,b){const A=weightKey(a),B=weightKey(b);if(A&&B)return A===B;if(A&&!B)return true;if(!A&&B)return true;return true}
function makeOffer(f,org,o){const r=rank(o,org.name),fr=rank(f,org.name);const title=champ(f)&&r>=1&&r<=5;let purse=n(org.purse,1000);try{if(typeof contractTerms==='function')purse=n(contractTerms(f,org).purse,purse)}catch(e){}purse=Math.max(250,Math.round(purse*(.85+Math.random()*.3)));if(title)purse=Math.round(purse*1.8);else if(fr<=5&&r<=5)purse=Math.round(purse*1.35);return{id:'O'+Date.now()+Math.random(),org:org.name,short:org.short,opponent:{...o},opponentRank:r,ranked:r<999,type:title?'ТИТУЛЬНЫЙ БОЙ':r<999?'РЕЙТИНГОВЫЙ БОЙ':'ОБЫЧНЫЙ БОЙ',titleFight:title,rounds:title?5:3,date:day()+(typeof rand==='function'?rand(14,45):21),purse,event:(typeof choice==='function'?choice(['Fight Night','Championship Series','Main Event']):'Fight Night')+' #'+(typeof rand==='function'?rand(10,99):50),expires:day()+7}}
function generate(f){ensure(f);if(f.nextFight){msg('У бойца уже есть назначенный бой');return[]}if(n(f.offerCooldownUntil)>day()){msg(`Новые предложения через ${n(f.offerCooldownUntil)-day()} дней`);return[]}
 const os=orgList();let orgs=[];if(f.contract?.org){orgs=[{name:f.contract.org,short:f.contract.org,purse:n(f.contract.purse,1000),level:n(f.contract.level,1)}]}else{orgs=os.filter(o=>o.name!=='DWCS');if(!orgs.length)orgs=[{name:'Regional League',short:'REG',purse:1000,level:1},{name:'Fight Night',short:'FN',purse:1500,level:2},{name:'Championship Series',short:'CS',purse:2500,level:3}]}
 const count=f.contract?Math.max(1,typeof rand==='function'?rand(1,3):1):Math.max(1,typeof rand==='function'?rand(1,5):3);const out=[];const used=new Set();for(const org of orgs.slice().sort(()=>Math.random()-.5)){if(out.length>=count)break;if(used.has(org.name))continue;used.add(org.name);const pool=candidatePool(f,org);if(pool.length)out.push(makeOffer(f,org,pool[0]))}
 if(out.length<count&&!f.contract){for(let i=0;i<os.length&&out.length<count;i++){const org=os[i];if(org.name==='DWCS'||used.has(org.name))continue;const pool=candidatePool(f,org);if(pool.length){used.add(org.name);out.push(makeOffer(f,org,pool[0]))}}}
 if(out.length<count){const fallbackOrg=f.contract?.org?{name:f.contract.org,short:f.contract.org,purse:n(f.contract.purse,1000),level:n(f.contract.level,1)}:(orgs[0]||{name:'Regional League',short:'REG',purse:1000,level:1});const all=fighterSources().filter(x=>available(x)&&x.id!==f.id&&sameWeightLoose(x,f));if(all.length){const usedOpp=new Set(out.map(o=>o.opponent.id));for(const x of all){if(out.length>=count)break;if(usedOpp.has(x.id))continue;usedOpp.add(x.id);out.push(makeOffer(f,fallbackOrg,x))}}}
 f.organizationOffers=out;f.refusalOfferBatchSize=out.length;saveSafe();return out}
function render(f,offers){const modal=document.getElementById('modal'),sheet=document.getElementById('sheet');if(!modal||!sheet){msg('Ошибка окна организации боя');return}modal.classList.add('open');sheet.innerHTML=`<div class="eyebrow">ОРГАНИЗАЦИЯ БОЯ</div><div class="title">Предложения для ${f.name}</div><div class="muted">${f.contract?'Контракт: '+f.contract.org+' • '+f.contract.fightsLeft+'/'+f.contract.length+' боёв':'Свободный агент • предложения из разных лиг'}</div><div class="list">${offers.map((o,i)=>`<div class="scout"><div class="fighter-top"><div class="scout-face">${typeof emoji==='function'?emoji(o.opponent.style):'🥊'}</div><div class="fighter-info"><div class="fighter-name">${o.opponent.flag||'🌍'} ${o.opponent.name}</div><div class="fighter-sub">${o.org} • ${o.opponent.country||''} • ${typeof rec==='function'?rec(o.opponent):''} • #${o.opponentRank||'—'}</div></div><div class="score">${typeof ovr==='function'?ovr(o.opponent):'—'}</div></div><div class="tags"><span class="tag">${o.org}</span><span class="tag">${o.type}</span><span class="tag">${o.rounds} раундов</span><span class="tag">${typeof dateLabel==='function'?dateLabel(o.date):o.date}</span><span class="tag">$${o.purse.toLocaleString('ru-RU')}</span></div><div class="scout-actions"><button data-org-profile="${i}">Профиль</button><button class="primary" data-org-negotiate="${i}">Организовать бой</button><button class="red" data-org-refuse="${i}">Отказаться</button></div></div>`).join('')}</div><div class="sheet-actions"><button data-org-close>Закрыть</button></div>`;sheet.querySelector('[data-org-close]').onclick=closeSafe;sheet.querySelectorAll('[data-org-profile]').forEach(b=>b.onclick=()=>{try{profile(offers[+b.dataset.orgProfile].opponent,'match')}catch(e){}});sheet.querySelectorAll('[data-org-negotiate]').forEach(b=>b.onclick=()=>negotiate(f,offers[+b.dataset.orgNegotiate]));sheet.querySelectorAll('[data-org-refuse]').forEach(b=>b.onclick=()=>refuse(f,offers[+b.dataset.orgRefuse]));}
function negotiate(f,o){const sheet=document.getElementById('sheet'),min=Math.max(250,Math.round(o.purse*.65)),max=Math.max(min,Math.round(o.purse*1.65));sheet.innerHTML=`<div class="eyebrow">ПЕРЕГОВОРЫ</div><div class="title">${f.name} vs ${o.opponent.name}</div><div class="muted">${o.org} • ${o.type}</div><section class="panel"><div class="row"><span>Предложено</span><b>$${o.purse.toLocaleString('ru-RU')}</b></div><div><label class="muted">Гонорар, $</label><input id="orgSalary" class="input" type="number" min="${min}" max="${max}" value="${o.purse}"></div></section><div class="sheet-actions"><button data-org-back>Назад</button><button class="primary" data-org-agree>Организовать бой</button></div>`;sheet.querySelector('[data-org-back]').onclick=()=>render(f,f.organizationOffers||[]);sheet.querySelector('[data-org-agree]').onclick=()=>{const purse=Math.max(min,Math.min(max,n(document.getElementById('orgSalary').value,o.purse)));const chance=Math.max(20,Math.min(98,Math.round(90-Math.max(0,purse-o.purse)/Math.max(1,o.purse)*70)));if(Math.random()*100>chance){msg(o.org+': условия не согласованы.');return}accept(f,o,purse)}}
function accept(f,o,purse){ensure(f);f.organizationOffers=[];f.leagueOffers=[];f.fightResolved=false;f.nextFight={opponent:{...o.opponent},org:o.org,event:o.event,rounds:o.rounds,date:o.date,purse,rank:o.opponentRank,ranked:o.ranked,type:o.type,titleFight:o.titleFight,venue:typeof choice==='function'?choice(['Las Vegas Arena','Abu Dhabi Arena','Moscow Arena','Riyadh Arena']):'Arena',card:o.rounds===5?'MAIN EVENT':'MAIN CARD',oneFight:!f.contract};f.currentFightLeague=o.org;f.campWeek=1;f.campSchedule={};f.campPerformance=3;if(f.contract)f.contract.fightsLeft=Math.max(0,n(f.contract.fightsLeft,1)-1);f.reputationHooks.accepted=n(f.reputationHooks.accepted)+1;saveSafe();msg(`${f.name}: бой организован — ${o.org} vs ${o.opponent.name}`);closeSafe();try{page('home')}catch(e){}}
function refuse(f,o){ensure(f);f.organizationOffers=(f.organizationOffers||[]).filter(x=>x.id!==o.id);f.reputationHooks.refused=n(f.reputationHooks.refused)+1;saveSafe();if(f.organizationOffers.length){render(f,f.organizationOffers);return}closeSafe();msg('Предложения отклонены')}
function matchmake(){const f=F();if(!f){msg('Выбери бойца');return}ensure(f);if(!f.agencyManaged){msg('Сначала подпиши бойца в своё агентство');return}if(f.nextFight){msg('У бойца уже есть назначенный бой');return}const existing=(f.organizationOffers||[]).filter(x=>n(x.expires)>=day()&&!x.resolved);const offers=existing.length?existing:generate(f);if(!offers.length){msg('Сейчас нет подходящих предложений.');return}render(f,offers)}
window.matchmake=matchmake;window._matchmakeHeavy=matchmake;window.MMA_MANAGER_V64_ORGANIZATION=true;
})();